#!/bin/bash

echo "START RACE!" > my_pipe
echo "ADDCAR TEAM: A, CAR: 20, SPEED: 30, CONSUMPTION: 0.04, RELIABILITY: 95"> my_pipe
echo "ADDCAR TEAM: B, CAR: 01, SPEED: 32, CONSUMPTION: 0.04, RELIABILITY: 90"> my_pipe
echo "ADDCAR TEAM: B, CAR: 01, SPEED: 33, CONSUMPTION: 0.05, RELIABILITY: 92"> my_pipe
echo "ADDCAR TEAM: B, CAR: 04, SPEED: 34, CONSUMPTION: 0.06, RELIABILITY: 91"> my_pipe
echo "ADDCAR TEAM: B, CAR: 05, SPEED: 34, CONSUMPTION: 0.06, RELIABILITY: 91"> my_pipe
echo "ADDCAR TEAM: C, CAR: 01, SPEED: 32, CONSUMPTION: 0.04, RELIABILITY: 90"> my_pipe
echo "START RACE!"> my_pipe
echo "ADDCAR TEAM: B, CAR: 05, SPEED: 34, CONSUMPTION: 0.06, RELIABILITY: 91"> my_pipe
echo "ADDCAR TEAM: C, CAR: 01, SPEED: 32, CONSUMPTION: 0.04, RELIABILITY: 90"> my_pipe